INSERT INTO degree (id, code, name) VALUES
    (gen_random_uuid(), 1001, 'Medicina'),
    (gen_random_uuid(), 1002, 'Psicología'),
    (gen_random_uuid(), 1003, 'Auditoría'),
    (gen_random_uuid(), 1004, 'Administración Hotelera'),
    (gen_random_uuid(), 1005, 'Nutricion'),
    (gen_random_uuid(), 1006, 'Diseño Gráfico'),
    (gen_random_uuid(), 1007, 'Ingeniería Electrónica'),
    (gen_random_uuid(), 1008, 'Derecho'),
    (gen_random_uuid(), 1009, 'Arquitectura'),
    (gen_random_uuid(), 1010, 'Administración de Empresas'),
    (gen_random_uuid(), 1011, 'Contaduría Pública'),
    (gen_random_uuid(), 1012, 'Economía'),
    (gen_random_uuid(), 1013, 'Enfermería'),
    (gen_random_uuid(), 1014, 'Física'),
    (gen_random_uuid(), 1015, 'Matemáticas'),
    (gen_random_uuid(), 1016, 'Biología'),
    (gen_random_uuid(), 1017, 'Química'),
    (gen_random_uuid(), 1018, 'Historia'),
    (gen_random_uuid(), 1019, 'Filosofía'),
    (gen_random_uuid(), 1020, 'Comunicación');